@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}


### GET /articles
GET {{baseUrl}}/articles

### GET /articles
GET {{baseUrl}}/articles?limit=1

### GET /articles/:id
GET {{baseUrl}}/article/4


### POST /article
POST {{baseUrl}}/article
Content-Type: application/json

{

    "reference":"EVYV123",
    "name": "vincent jogg addidas",
    "description":"jogging sport ",
    "image": "c:/repertoire/image/b",
    "color":"blanche",
    "pre_tax_price": "30",
    "vat_rate": "20",
    "discount": "20",
    "categories":2
}


### PUT /article/:id
PUT {{baseUrl}}/article/5
Content-Type: application/json

{
    "reference":"Abdoulla le MOOOOCHE",
    "name": "capuche",
    "description":"tshirt BLEU",
    "image": "c:/repertoire/image/b",
    "color":"blue",
    "pre_tax_price": 30,
    "vat_rate": 20,
    "discount": 20,
    "categories": [
        {
            "category_id": 2,
            "old_category_id": 3
        }
    ]
}

###  DELETE /article/:id
DELETE {{baseUrl}}/article/4


# ****************************
# ****************************
###  GET /categories
GET {{baseUrl}}/categories

### GET /category/:id
GET {{baseUrl}}/category/1

### POST /category/:id
POST {{baseUrl}}/category
Content-Type: application/json

{
    "title": "décontracté"
}

### PUT /category/:id
PUT {{baseUrl}}/category/1
Content-Type: application/json

{
    "title": "patch"
}

### DELETE /category/:id
DELETE {{baseUrl}}/category/2


# ****************************
# ****************************
###  GET /orders
GET {{baseUrl}}/orders

### GET /order/:id
GET {{baseUrl}}/order/5

### POST /order/:id
POST {{baseUrl}}/order
Content-Type: application/json

{
    "order_number": 1,
    "total_price": 20,
    "address_id": 1
}

### PUT /order/:id
PUT {{baseUrl}}/order/4
Content-Type: application/json

{
    "order_number": 20,
    "total_price": 130,
    "address_id": 1
}

### DELETE /order/:id
DELETE {{baseUrl}}/order/1


# ****************************
# **************************** 
### GET /users
GET {{baseUrl}}/users

### GET /users/:id
GET {{baseUrl}}/user/2

### POST /user/
POST {{baseUrl}}/user
Content-Type: application/json

{
"email": "RdtSZAZzSdzzefvxs@gmail.com",
"password":"enceneee"
}

###POST /signup/
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "email":"RdtSZAZzSdzzefvxs@gmail.com",
    "firstname":"rard",
    "lastname":"poulpos",
    "password":"enceneee",
    "passwordConfirm":"enceneee",
    "phone_number":"0123456789",
    "role_id": 1,
    "country": "France",
    "city": "marignane",
    "zip_code": "13000",
    "number": 10,
    "street_name": "rue de Vincent",
    "additional":"étage 5",
    "user_id": 1
}
###PUT /user/:id
PUT {{baseUrl}}/user/4
Content-Type: application/json

{
    "email":"chuvak@gmail.com",
    "firstname":"test patch",
    "lastname":"patch",
    "password":"brbr",
    "phone_number":"000123456789",
    "role_id": 1
}

###DELETE /user/:id
DELETE {{baseUrl}}/user/4


# ****************************
# ****************************
# ADDRESS
###  GET /addresses
GET {{baseUrl}}/addresses

### GET /address/:id
GET {{baseUrl}}/address/1


### POST /address/:id
POST {{baseUrl}}/address
Content-Type: application/json

{
    "country": "France",
    "city": "marignane",
    "zip_code": "13000",
    "number": 10,
    "street_name": "rue de Vincent",
    "additional":"étage 5",
    "user_id": 1
}

### PUT /address/:id
PUT {{baseUrl}}/address/1
Content-Type: application/json

{
    "country": "France",
    "city": "Aix",
    "zip_code": "83000",
    "number": 11,
    "street_name": "rue de Mega",
    "additional": "étage 8",
    "user_id": 1
}

### DELETE /address/:id
DELETE {{baseUrl}}/address/1


# ****************************
# ****************************

# SIZES
###  GET /sizes
GET {{baseUrl}}/sizes

### GET /size/:id
GET {{baseUrl}}/size/3


### POST /size/
POST {{baseUrl}}/size
Content-Type: application/json

{
    "size_name": "taille 1"
}

### PUT /size/:id
PUT {{baseUrl}}/size/3
Content-Type: application/json

{
    "size_name": "S-28"
}
### DELETE /size/:id
DELETE {{baseUrl}}/size/11