@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}


### GET
GET {{baseUrl}}/articles

### GET
GET {{baseUrl}}/articles?limit=3

### GET
GET {{baseUrl}}/article/11

### POST
POST {{baseUrl}}/article
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJFbWFpbCI6ImVhZEBnbWFpbC5jb20iLCJpYXQiOjE2MTYwNjU2MDcsImV4cCI6MTYxNjA2OTIwN30.XuBQQ93NrlVnkK7hb0saM6NJDdl0JxTV3nP3VUDfY8k

{
    "reference": "111222222",
    "name": "Chuvak",
    "description": "blanc",
    "image": "image/link",
    "color": "blue",
    "pre_tax_price": 10,
    "vat_rate": 20,
    "discount": 30,
    "categories": [
        {
        "title": "CHAKAL"
        }
    ],
    "sizes": [
      {
        "size_name": "SLLL",
        "stock": 12
      },
      {
        "size_name": "M",
        "stock": 10
      }
    ]
}

### PUT /articles/:id
PUT {{baseUrl}}/article/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJFbWFpbCI6ImVhZEBnbWFpbC5jb20iLCJpYXQiOjE2MTYwNjU2MDcsImV4cCI6MTYxNjA2OTIwN30.XuBQQ93NrlVnkK7hb0saM6NJDdl0JxTV3nP3VUDfY8k

{
    "reference":"1402303239",
    "name": "Tee-shirt",
    "description":"tshirt BLEU",
    "image": "c:/repertoire/image/b",
    "color":"blue",
    "pre_tax_price": 30.90,
    "vat_rate": 27.4,
    "discount": 20.20,
    "categories": [
        {
            "title": "femme"
        }
    ],
    "sizes": [
      {
        "size_name": "TLLE TEST",
        "stock": 3330000
      },
      {
        "size_name": "Azaaze",
        "stock": 20000
      }
    ]
}

### DELETE
DELETE {{baseUrl}}/article/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJFbWFpbCI6InRvdG9AdGF0YS5mciIsImlhdCI6MTYxNjMxODkxMywiZXhwIjoxNjE2MzIyNTEzfQ.ovBEfDbExlr3s718_sezbzuacBZloqdWS7D8QNWlclQ

### GET
GET {{baseUrl}}/categories

### GET
GET {{baseUrl}}/category/1

### POST 
POST {{baseUrl}}/category
Content-Type: application/json

{
    "title": "décontracté"
}

### PUT /category/:id
PUT {{baseUrl}}/category/1
Content-Type: application/json

{
    "title": "PUT"
}

### DELETE
DELETE {{baseUrl}}/category/1


### GET
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInVzZXJFbWFpbCI6InRvdG9AdGF0YS5jb20iLCJpYXQiOjE2MTYwODUwNzMsImV4cCI6MTYxNjA4ODY3M30.OymZDdJBwINlVs3rKv0knT3MDTjo9549rjDraUyVT-w

### GET
GET {{baseUrl}}/order/1



### GET 
GET {{baseUrl}}/user-orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJFbWFpbCI6InRvdG9AdGF0YS5jb20iLCJpYXQiOjE2MTYxNDUxNTMsImV4cCI6MTYxNjE0ODc1M30.4ZzAepq9IBxrpygw49Sma2OzwRX0s-FZ3P5gdfLeGV8

### POST
POST {{baseUrl}}/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJFbWFpbCI6ImVhZEBnbWFpbC5jb20iLCJpYXQiOjE2MTYwNjU2MDcsImV4cCI6MTYxNjA2OTIwN30.XuBQQ93NrlVnkK7hb0saM6NJDdl0JxTV3nP3VUDfY8k

{
    // "order_number": à créer en back
    "user_id": 2,
    "address_id": 2,
    "total_price": "200",
    "quantity_total": 10,
    "articles": [
        {
            "article_id": 1,
            "unit_net_price": 10,
            "sizes": {
                "size": "L",
                "quantity": 3
            }
        },
        {
            "article_id": 2,
            "unit_net_price": 10,
            "sizes": {
                "size": "XL",
                "quantity": 3
            }
        }
    ]
}


### PUT
PUT {{baseUrl}}/order/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJFbWFpbCI6ImVhZEBnbWFpbC5jb20iLCJpYXQiOjE2MTYwNjU2MDcsImV4cCI6MTYxNjA2OTIwN30.XuBQQ93NrlVnkK7hb0saM6NJDdl0JxTV3nP3VUDfY8k

{
    "status_name": "confirmed",
    "tracking_number":""
}


### GET
GET {{baseUrl}}/users

### GET
GET {{baseUrl}}/user/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJFbWFpbCI6InRvdG9AdGF0YS5jb20iLCJpYXQiOjE2MTYxNTExMzIsImV4cCI6MTYxNjE1NDczMn0.Dbq1rNm4fm0ZCLM7dXEq_9jgv3Ozdd9gq5-tU_BuVA4


### POST
POST {{baseUrl}}/user
Content-Type: application/json
#les users seeding ne marche pas à cause de bcrypt

{
"email": "toto@tata.fr",
"password":"123456789"
}

### POST
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "email":"toto@tata.fr",
    "firstname":"rard",
    "lastname":"poulpos",
    "password":"123456789",
    "passwordConfirm":"123456789",
    "phoneNumber":"0123456789",
    "roleId": 1,
    "country": "France",
    "city": "marignane",
    "zipCode": "13000",
    "number": 10,
    "streetName": "rue de Vincent",
    "additional":"étage 5"
}

###PUT /user/:id
PUT {{baseUrl}}/user/2
Content-Type: application/json

{
    "email":"chvak@gmail.com",
    "firstname":"test PUT",
    "lastname":"PUT",
    "password":"brbr",
    "phone_number":"000123456789",
    "role_id": 1
}

### DELETE /user/:id

DELETE {{baseUrl}}/user/1



### GET
GET {{baseUrl}}/addresses

### GET
GET {{baseUrl}}/address/1

### POST
POST {{baseUrl}}/address
Content-Type: application/json

{
    "country": "France",
    "city": "marignane",
    "zipCode": "13000",
    "number": 10,
    "streetName": "rue de Vincent",
    "additional":"étage 5",
    "firstNameAddress":"Noël",
    "lastNameAddress":"Flantier",
    "userId": 2
}


### PUT /addresses/:id
PUT {{baseUrl}}/address/16
Content-Type: application/json

{
    "country": "France",
    "city": "Aix",
    "zipCode": "83000",
    "number": 11,
    "streetName": "rue de Mega",
    "additional": "étage 8",
    "firstNameAddress":"Noël",
    "lastNameAddress":"cagette",
    "userId": 2
}

### DELETE
DELETE {{baseUrl}}/address/3


# SIZES
### GET
GET {{baseUrl}}/sizes

### GET
GET {{baseUrl}}/size/16


### POST
POST {{baseUrl}}/size
Content-Type: application/json

{
    "size_name": "taille test"
}

### PUT /sizes/:id
PUT {{baseUrl}}/size/16
Content-Type: application/json

{
    "size_name": "45"
}
### DELETE
DELETE {{baseUrl}}/size/16


### POST
POST {{baseUrl}}/pay
Content-Type: application/json

{

}


### GET
GET {{baseUrl}}/status

### GET
GET {{baseUrl}}/status/7

### POST
POST {{baseUrl}}/status
Content-Type: application/json

{
    "status_name": "test"
}

### PUT
PUT {{baseUrl}}/status/7
Content-Type: application/json

{
    "status_name": "re test"
}

### DELETE
DELETE {{baseUrl}}/status/7