@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}


### GET
GET {{baseUrl}}/articles

### GET
GET {{baseUrl}}/articles?limit=3

### GET
GET {{baseUrl}}/article/11

### POST
POST {{baseUrl}}/article
Content-Type: application/json

{
    "reference": "111222222",
    "name": "Chuvak",
    "description": "blanc",
    "image": "image/link",
    "color": "blue",
    "pre_tax_price": 10,
    "vat_rate": 20,
    "discount": 30,
    "categories": [
        {
        "title": "CHAKAL"
        }
    ],
    "sizes": [
      {
        "size_name": "SLLL",
        "stock": 12
      },
      {
        "size_name": "M",
        "stock": 10
      }
    ]
}

### PUT /articles/:id
PUT {{baseUrl}}/article/1
Content-Type: application/json

{
    "reference":"1402303239",
    "name": "Tee-shirt",
    "description":"tshirt BLEU",
    "image": "c:/repertoire/image/b",
    "color":"blue",
    "pre_tax_price": 30,
    "vat_rate": 20,
    "discount": 20,
    "categories": [
        {
            "title": "homme"
        }
    ],
    "sizes": [
      {
        "size_name": "TAILLE TEST",
        "stock": 3330000
      },
      {
        "size_name": "L",
        "stock": 20000
      }
    ]
}

### DELETE
DELETE {{baseUrl}}/article/11


### GET
GET {{baseUrl}}/categories

### GET
GET {{baseUrl}}/category/1

### POST 
POST {{baseUrl}}/category
Content-Type: application/json

{
    "title": "décontracté"
}

### PUT /categories/:id
PUT {{baseUrl}}/categories/1
Content-Type: application/json

{
    "title": "PUT"
}

### DELETE
DELETE {{baseUrl}}/category/11


### GET
GET {{baseUrl}}/orders

### GET
GET {{baseUrl}}/order/10

### POST
POST {{baseUrl}}/order
Content-Type: application/json

{
    // "order_number": à créer en back
    "user_id": 2,
    "address_id": 2,
    "total_price": "200",
    "articles": [
        {
            "article_id": 4,
            "quantity": 10,
            "unit_net_price": 10
        },
        {
            "article_id": 5,
            "quantity": 10,
            "unit_net_price": 10
        },
        {
            "article_id": 2,
            "quantity": 11,
            "unit_net_price": 11
        }
    ]
}


### GET
GET {{baseUrl}}/users

### GET
GET {{baseUrl}}/user/34


### POST
POST {{baseUrl}}/user
Content-Type: application/json
#les users seeding ne marche pas à cause de bcrypt

{
"email": "vincen@gmail.com",
"password":"ABCDEFGH"
}

### POST
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "email":"vin@gmail.com",
    "firstname":"rard",
    "lastname":"poulpos",
    "password":"ABCDEFGH",
    "passwordConfirm":"ABCDEFGH",
    "phoneNumber":"0123456789",
    "roleId": 1,
    "country": "France",
    "city": "marignane",
    "zipCode": "13000",
    "number": 10,
    "streetName": "rue de Vincent",
    "additional":"étage 5"
}

###PUT /user/:id
PUT {{baseUrl}}/user/2

Content-Type: application/json

{
    "email":"chvak@gmail.com",
    "firstname":"test PUT",
    "lastname":"PUT",
    "password":"brbr",
    "phone_number":"000123456789",
    "role_id": 1
}

### DELETE /user/:id

DELETE {{baseUrl}}/user/4



### GET
GET {{baseUrl}}/addresses

### GET
GET {{baseUrl}}/address/3

### POST
POST {{baseUrl}}/addresses
Content-Type: application/json

{
    "country": "France",
    "city": "marignane",
    "zip_code": "13000",
    "number": 10,
    "street_name": "rue de Vincent",
    "additional":"étage 5",
    "user_id": 1
}


### PUT /addresses/:id
PUT {{baseUrl}}/addresses/1
Content-Type: application/json

{
    "country": "France",
    "city": "Aix",
    "zip_code": "83000",
    "number": 11,
    "street_name": "rue de Mega",
    "additional": "étage 8",
    "user_id": 1
}

### DELETE
DELETE {{baseUrl}}/addresses/5


# SIZES
### GET
GET {{baseUrl}}/sizes

### GET
GET {{baseUrl}}/size/14


### POST
POST {{baseUrl}}/sizes
Content-Type: application/json

{
    "size_name": "taille test"
}

### PUT /sizes/:id
PUT {{baseUrl}}/sizes/3
Content-Type: application/json

{
    "size_name": "45"
}
### DELETE
DELETE {{baseUrl}}/size/12


### POST
POST {{baseUrl}}/pay
Content-Type: application/json

{

}
